package main

# Tenant Applications must never run under the "default" AppProject - that's the whole point of
# charts/tenant-project. Only platform-owned bootstrap Applications may use "default".
deny[msg] {
	input.kind == "Application"
	endswith(input.metadata.name, "-airflow")
	input.spec.project == "default"
	msg := sprintf("Application %q is a tenant Airflow app but uses the 'default' AppProject", [input.metadata.name])
}

deny[msg] {
	input.kind == "Application"
	contains(input.metadata.name, "-workloads-")
	input.spec.project == "default"
	msg := sprintf("Application %q is a tenant workloads app but uses the 'default' AppProject", [input.metadata.name])
}

# Tenant AppProjects must not whitelist any cluster-scoped resources.
deny[msg] {
	input.kind == "AppProject"
	count(input.spec.clusterResourceWhitelist) > 0
	msg := sprintf("AppProject %q whitelists cluster-scoped resources: %v", [input.metadata.name, input.spec.clusterResourceWhitelist])
}

# No ":latest" image tags anywhere.
deny[msg] {
	input.kind == "Pod"
	container := input.spec.containers[_]
	endswith(container.image, ":latest")
	msg := sprintf("Pod %q container %q uses a ':latest' image tag: %v", [input.metadata.name, container.name, container.image])
}

deny[msg] {
	some kind
	kind == {"Deployment", "StatefulSet", "Job"}[_]
	input.kind == kind
	container := input.spec.template.spec.containers[_]
	endswith(container.image, ":latest")
	msg := sprintf("%s %q container %q uses a ':latest' image tag: %v", [input.kind, input.metadata.name, container.name, container.image])
}

# Automated sync must keep prune+selfHeal on for every Application generated by this repo -
# silently disabling either defeats the whole "GitOps as ground truth" premise.
deny[msg] {
	input.kind == "Application"
	sp := input.spec.syncPolicy.automated
	sp.prune != true
	msg := sprintf("Application %q has automated sync but prune is not true", [input.metadata.name])
}

deny[msg] {
	input.kind == "Application"
	sp := input.spec.syncPolicy.automated
	sp.selfHeal != true
	msg := sprintf("Application %q has automated sync but selfHeal is not true", [input.metadata.name])
}
