apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres-lite.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ .Values.nameOverride }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ .Values.nameOverride }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: postgres
      port: {{ .Values.port }}
      targetPort: postgres
