extends: default
ignore: |
  charts/*/charts/
  charts/*/templates/
  .local/
rules:
  line-length:
    max: 140
    level: warning
  document-start: disable
  truthy:
    allowed-values: ["true", "false", "on"]
  comments-indentation: disable
  braces:
    max-spaces-inside: 1
