scope: namespace
tenant: tenant-ci
namespace: tenant-ci-workloads
isWorkloadNamespace: true
workloadRunnerServiceAccount: tenant-ci-workload-runner
localAirflowServiceAccountNamespace: tenant-ci-airflow
